/**
 * @file MostPlayedPlaylistCreatorTest.java
 * Classe di test per {@link MostPlayedPlaylistCreator}.
 *
 * <p>Verifica che il Factory Method {@code createPlaylist()} filtri correttamente
 * le tracce con almeno una riproduzione e le ordini in modo decrescente per
 * {@code playCount}, restituendo {@code null} quando nessuna traccia è stata
 * riprodotta.</p>
 *
 * @author EmanuelChirico
 */
package it.unisa.diem.sad_gruppo6.controllers;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.factory.MostPlayedPlaylistCreator;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class MostPlayedPlaylistCreatorTest {

    private MostPlayedPlaylistCreator creator;
    private Track trackA;
    private Track trackB;
    private Track trackC;

    /**
     * Setup eseguito prima di ogni test.
     * Crea tre tracce con file .mp3 temporanei e {@code playCount} iniziale a 0.
     */
    @BeforeEach
    public void setUp() throws IOException {
        creator = new MostPlayedPlaylistCreator();

        File fa = File.createTempFile("trackA_", ".mp3"); fa.deleteOnExit();
        File fb = File.createTempFile("trackB_", ".mp3"); fb.deleteOnExit();
        File fc = File.createTempFile("trackC_", ".mp3"); fc.deleteOnExit();

        trackA = new Track("Song A", "Artist A", 200, "Rock", 2000, fa.getAbsolutePath());
        trackB = new Track("Song B", "Artist B", 180, "Pop",  2005, fb.getAbsolutePath());
        trackC = new Track("Song C", "Artist C", 240, "Jazz", 2010, fc.getAbsolutePath());
    }

    /**
     * Con lista vuota il metodo deve restituire null.
     */
    @Test
    public void testEmptyListReturnsNull() {
        assertNull(creator.createPlaylist(new ArrayList<>()));
    }

    /**
     * Se nessuna traccia è stata riprodotta (playCount == 0 per tutte)
     * il metodo deve restituire null.
     */
    @Test
    public void testNoPlayedTracksReturnsNull() {
        List<Track> tracks = List.of(trackA, trackB, trackC);
        assertNull(creator.createPlaylist(tracks));
    }

    /**
     * Se solo alcune tracce hanno playCount > 0, la playlist deve contenere
     * soltanto quelle, escludendo le non riprodotte.
     */
    @Test
    public void testOnlyPlayedTracksAreIncluded() {
        trackA.incrementPlayCount(); // playCount = 1
        // trackB e trackC restano a 0

        Playlist playlist = creator.createPlaylist(List.of(trackA, trackB, trackC));

        assertNotNull(playlist);
        assertEquals(1, playlist.getNumTracks());
        assertTrue(playlist.getTracks().contains(trackA));
        assertFalse(playlist.getTracks().contains(trackB));
        assertFalse(playlist.getTracks().contains(trackC));
    }

    /**
     * Le tracce devono essere ordinate in ordine decrescente di playCount:
     * la traccia più ascoltata deve essere in posizione 0.
     */
    @Test
    public void testTracksAreOrderedByPlayCountDescending() {
        trackA.incrementPlayCount();                       // playCount = 1
        trackB.incrementPlayCount(); trackB.incrementPlayCount(); // playCount = 2
        trackC.incrementPlayCount(); trackC.incrementPlayCount(); trackC.incrementPlayCount(); // playCount = 3

        Playlist playlist = creator.createPlaylist(List.of(trackA, trackB, trackC));

        assertNotNull(playlist);
        List<Track> result = playlist.getTracks();
        assertEquals(trackC, result.get(0)); // 3 riproduzioni
        assertEquals(trackB, result.get(1)); // 2 riproduzioni
        assertEquals(trackA, result.get(2)); // 1 riproduzione
    }

    /**
     * La playlist restituita deve avere il nome {@code "Most Played"}.
     */
    @Test
    public void testPlaylistHasCorrectName() {
        trackA.incrementPlayCount();

        Playlist playlist = creator.createPlaylist(List.of(trackA));

        assertEquals(MostPlayedPlaylistCreator.PLAYLIST_NAME, playlist.getName());
    }

    /**
     * La playlist deve essere marcata come autogenerata ({@code isAutoGenerated == true}).
     */
    @Test
    public void testPlaylistIsAutoGenerated() {
        trackA.incrementPlayCount();

        Playlist playlist = creator.createPlaylist(List.of(trackA));

        assertTrue(playlist.isAutoGenerated());
    }

    /**
     * Se tutte le tracce sono state riprodotte, la playlist deve contenerle tutte
     * nel corretto ordine decrescente.
     */
    @Test
    public void testAllTracksPlayedAreAllIncluded() {
        trackA.incrementPlayCount();
        trackB.incrementPlayCount(); trackB.incrementPlayCount();
        trackC.incrementPlayCount();

        Playlist playlist = creator.createPlaylist(List.of(trackA, trackB, trackC));

        assertNotNull(playlist);
        assertEquals(3, playlist.getNumTracks());
        assertEquals(trackB, playlist.getTracks().get(0)); // 2 riproduzioni — prima
    }

    /**
     * Con una sola traccia riprodotta la playlist deve contenerne esattamente una.
     */
    @Test
    public void testSinglePlayedTrackCreatesPlaylistWithOneTrack() {
        trackA.incrementPlayCount();

        Playlist playlist = creator.createPlaylist(List.of(trackA));

        assertNotNull(playlist);
        assertEquals(1, playlist.getNumTracks());
        assertEquals(trackA, playlist.getTracks().get(0));
    }
}
