/**
 * @file GenrePlaylistCreator.java
 * @brief ConcreteCreator del pattern Factory Method per la generazione automatica
 *        di playlist filtrate per genere musicale.
 *
 * @details Estende PlaylistCreator e implementa createPlaylist(List)
 *          selezionando dalla TrackLibrary tutte le tracce il cui genere corrisponde
 *          (case-insensitive) a quello ricevuto nel costruttore.
 *          La playlist prodotta ha isAutoGenerated = true e come nome
 *          il genere stesso.
 *
 * @pattern Factory Method
 * @see PlaylistCreator
 * @see Playlist
 *
 * @author EmanuelaGraziuso
 */
package it.unisa.diem.sad_gruppo6.model.factory;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;

import java.util.List;

public class GenrePlaylistCreator extends PlaylistCreator {

    /** Il genere musicale usato come criterio di filtraggio. */
    private final String genre;

    /**
     * @brief Costruttore del GenrePlaylistCreator.
     *
     * @param genre Il genere musicale in base al quale filtrare le tracce.
     *              Non deve essere null né vuoto.
     * @throws IllegalArgumentException Se il genere è null.
     */
    public GenrePlaylistCreator(String genre) {
        if (genre == null || genre.isBlank()) {
            throw new IllegalArgumentException("Il genere non può essere vuoto.");
        }
        this.genre = genre;
    }

    /**
     * @brief Crea una playlist automatica con tutte le tracce del genere specificato.
     *
     * @details Itera su tracks e aggiunge alla playlist ogni traccia il cui
     *          genere corrisponde (confronto case-insensitive) a genre.
     *          Il nome della playlist è uguale al genere e isAutoGenerated
     *          è impostato a true.
     *          Restituisce null se nessuna traccia appartiene al genere,
     *          così il chiamante può decidere di non creare né mantenere la playlist.
     *
     * @param tracks La lista completa di tracce della TrackLibrary.
     * @return Una Playlist con isAutoGenerated = true e nome uguale
     *         al genere, oppure null se non ci sono tracce del genere.
     */
    @Override
    public Playlist createPlaylist(List<Track> tracks) {
        Playlist playlist = new Playlist(genre, true);

        for (Track t : tracks) {
            if (t.getGenre() != null && t.getGenre().equalsIgnoreCase(genre)) {
                playlist.addTrack(t);
            }
        }

        // Se nessuna traccia appartiene al genere, non restituiamo una playlist vuota
        if (playlist.getTracks().isEmpty()) {
            return null;
        }

        return playlist;
    }

    /**
     * @brief Restituisce il genere associato a questo creator.
     * @return Il genere musicale usato come criterio.
     */
    public String getGenre() {
        return genre;
    }
}
