/**
 * @file PlaylistCreator.java
 * @brief Classe astratta che definisce il Factory Method per la creazione di playlist automatiche.
 *
 * @details Ogni ConcreteCreator (es. GenrePlaylistCreator) estende questa classe e
 * implementa createPlaylist(List) applicando il proprio criterio di filtraggio
 * sulla lista di tracce fornita dalla TrackLibrary. Il pattern Factory Method permette
 * al PlaylistController di rimanere completamente indipendente dai criteri di
 * generazione specifici.
 *
 * @pattern Factory Method
 *
 * @author EmanuelaGraziuso
 */

package it.unisa.diem.sad_gruppo6.model.factory;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;

import java.util.List;

public abstract class PlaylistCreator {

    /**
     * @brief Factory Method: crea e restituisce una Playlist automatica
     *        a partire dalla lista di tracce della libreria.
     *
     * @details Le sottoclassi concrete implementano questo metodo applicando
     *          il proprio criterio di selezione (genere, anno, playCount, ecc.).
     *          La playlist restituita ha sempre isAutoGenerated = true.
     *
     * @param tracks La lista completa delle tracce presenti nella TrackLibrary.
     * @return Una nuova istanza di Playlist con isAutoGenerated = true,
     *         oppure null se nessuna traccia soddisfa il criterio.
     */
    public abstract Playlist createPlaylist(List<Track> tracks);
}
