/**
 * @file YearPlaylistCreator.java
 * @brief ConcreteCreator del pattern Factory Method per la generazione automatica
 *        di playlist filtrate per anno di pubblicazione.
 *
 * @details Estende PlaylistCreator e implementa createPlaylist(List)
 *          selezionando dalla TrackLibrary tutte le tracce il cui anno corrisponde
 *          a quello ricevuto nel costruttore.
 *          La playlist prodotta ha isAutoGenerated = true e come nome
 *          l'anno stesso come stringa (es. "2023").
 *          Restituisce null se nessuna traccia appartiene all'anno,
 *          così il chiamante può decidere di non creare né mantenere la playlist.
 *
 * @pattern Factory Method
 * @see PlaylistCreator
 * @see Playlist
 *
 * @author EmanuelaGraziuso
 */
package it.unisa.diem.sad_gruppo6.model.factory;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;

import java.util.List;

public class YearPlaylistCreator extends PlaylistCreator {

    private final int year;

    /**
     * @brief Costruttore del YearPlaylistCreator.
     *
     * @param year L'anno di pubblicazione in base al quale filtrare le tracce.
     *             Deve essere un valore positivo.
     * @throws IllegalArgumentException Se l'anno è <= 0.
     */
    public YearPlaylistCreator(int year) {
        if (year <= 0) {
            throw new IllegalArgumentException("L'anno non può essere <= 0.");
        }
        this.year = year;
    }

    /**
     * @brief Crea una playlist automatica con tutte le tracce dell'anno specificato.
     *
     * @details Itera su tracks e aggiunge alla playlist ogni traccia il cui
     *          anno corrisponde a year.
     *          Il nome della playlist è uguale all'anno come stringa e isAutoGenerated
     *          è impostato a true.
     *          Restituisce null se nessuna traccia appartiene all'anno,
     *          così il chiamante può decidere di non creare né mantenere la playlist.
     *
     * @param tracks La lista completa di tracce della TrackLibrary.
     * @return Una Playlist con isAutoGenerated = true e nome uguale
     *         all'anno, oppure null se non ci sono tracce dell'anno.
     */
    @Override
    public Playlist createPlaylist(List<Track> tracks) {
        Playlist playlist = new Playlist(String.valueOf(year), true);

        for (Track t : tracks) {
            if (t.getYear() == year) {
                playlist.addTrack(t);
            }
        }

        // Se nessuna traccia appartiene all'anno, non restituiamo una playlist vuota
        if (playlist.getTracks().isEmpty()) {
            return null;
        }

        return playlist;
    }

    /**
     * @brief Restituisce l'anno associato a questo creator.
     * @return L'anno di pubblicazione usato come criterio.
     */
    public int getYear() {
        return year;
    }
}