/**
 * @file ConcretePlaylist.java
 * @brief ConcreteProduct del pattern Factory Method.
 *
 * @details Implementazione concreta dell'interfaccia Playlist.
 * Istanziata dai ConcreteCreator (GenrePlaylistCreator, YearPlaylistCreator,
 * TagPlaylistCreator, MostPlayedPlaylistCreator) e da PlaylistController
 * per le playlist create manualmente dall'utente.
 *
 * @pattern Factory Method (ConcreteProduct)
 *
 * @author LuigiAutorino
 */

package it.unisa.diem.sad_gruppo6.model.domain;

import java.util.ArrayList;
import java.util.List;

import it.unisa.diem.sad_gruppo6.model.playback.iterators.PlaylistIterator;
import it.unisa.diem.sad_gruppo6.model.playback.strategies.PlaybackMode;

public class ConcretePlaylist implements Playlist {

    private String name;
    private List<Track> tracks;
    private boolean isAutoGenerated;

    /**
     * @param name            Il nome della playlist.
     * @param isAutoGenerated true se generata automaticamente dal sistema.
     */
    public ConcretePlaylist(String name, boolean isAutoGenerated) {
        this.name = name;
        this.isAutoGenerated = isAutoGenerated;
        this.tracks = new ArrayList<>();
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(String name) {
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Playlist name can't be empty.");
        }
        this.name = name;
    }

    @Override
    public List<Track> getTracks() {
        return tracks;
    }

    @Override
    public int getNumTracks() {
        if (this.tracks != null) {
            return this.tracks.size();
        }
        return 0;
    }

    @Override
    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    @Override
    public void addTrack(Track t) {
        if (!tracks.contains(t)) {
            tracks.add(t);
        }
    }

    @Override
    public void removeTrack(Track t) {
        if (!tracks.contains(t))
            throw new IllegalArgumentException("La traccia non è presente nella playlist.");
        tracks.remove(t);
    }

    @Override
    public void reorder(Track t, int newIndex) {
        int oldIndex = tracks.indexOf(t);
        if (oldIndex == -1) {
            throw new IllegalArgumentException("La traccia non è presente in questa playlist.");
        }
        if (newIndex < 0 || newIndex > tracks.size() - 1) {
            throw new IllegalArgumentException("Indice di destinazione non valido.");
        }
        tracks.remove(oldIndex);
        tracks.add(newIndex, t);
    }

    @Override
    public PlaylistIterator createIterator(PlaybackMode mode, Track startTrack) {
        return mode.getIterator(this.tracks, startTrack);
    }

    @Override
    public String toString() {
        return this.getName();
    }
}
