/**
 * @file Playlist.java
 * @brief Interfaccia Product del pattern Factory Method per le playlist.
 *
 * @details Definisce il contratto che ogni tipo di playlist deve rispettare,
 * indipendentemente dal criterio con cui è stata creata (utente, genere,
 * anno, tag, most-played). I ConcreteCreator del pattern Factory Method
 * restituiscono sempre questo tipo astratto.
 *
 * @pattern Factory Method (Product)
 *
 * @author LuigiAutorino
 */

package it.unisa.diem.sad_gruppo6.model.domain;

import java.util.List;

import it.unisa.diem.sad_gruppo6.model.playback.iterators.PlaylistIterator;
import it.unisa.diem.sad_gruppo6.model.playback.strategies.PlaybackMode;

public interface Playlist {

    /** @return Il nome della playlist. */
    String getName();

    /**
     * @param name Il nuovo nome da assegnare.
     * @throws IllegalArgumentException Se il nome è null o vuoto.
     */
    void setName(String name);

    /** @return La lista delle tracce contenute nella playlist. */
    List<Track> getTracks();

    /** @return Il numero di tracce presenti nella playlist. */
    int getNumTracks();

    /** @return true se la playlist è stata generata automaticamente dal sistema. */
    boolean isAutoGenerated();

    /**
     * Aggiunge una traccia evitando duplicati.
     * @param t La traccia da aggiungere.
     */
    void addTrack(Track t);

    /**
     * Rimuove una traccia dalla playlist.
     * @param t La traccia da rimuovere.
     * @throws IllegalArgumentException Se la traccia non è presente.
     */
    void removeTrack(Track t);

    /**
     * Sposta una traccia in una nuova posizione.
     * @param t        La traccia da spostare.
     * @param newIndex L'indice di destinazione.
     * @throws IllegalArgumentException Se la traccia non esiste o l'indice non è valido.
     */
    void reorder(Track t, int newIndex);

    /**
     * Crea l'iteratore appropriato per questa playlist delegando alla Strategy.
     * @param mode       La modalità di riproduzione attiva (Strategy).
     * @param startTrack La traccia da cui partire; null per partire dall'inizio.
     * @return Un PlaylistIterator configurato per la modalità richiesta.
     */
    PlaylistIterator createIterator(PlaybackMode mode, Track startTrack);
}
